#!/bin/bash

# Copyright (C) 2025 Free Software Foundation, Inc.
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Occasionally we add new stages to default_install_hook_types in
# .pre-commit-config.yaml.  The new stages are not used until somebody runs
# pre-commit install again.  This script, meant to run as a pre-commit hook in
# the pre-commit stage, detects this situation.

cfg=".pre-commit-config.yaml"

# This assumes that the default_install_hook_types setting is one line.
line=$(grep "default_install_hook_types" $cfg)
# Get the values in the list.
line=${line/*\[/}
line=${line/\]*/}
# Drop commas and quotes.
line=${line//[,\"\']/}
# shellcheck disable=SC2206 # Allow word splitting.
stages=($line)

if [ -f ".git" ]; then
    # Handle worktrees.
    line=$(grep "gitdir:" ".git")
    # shellcheck disable=SC2206 # Allow word splitting.
    line=($line)
    dir=${line[1]}/../..
else
    dir=.git
fi

if [ ! -d "$dir" ]; then
    echo "no .git dir found, skipping"
    exit 0
fi

for stage in "${stages[@]}"; do
    f=$dir/hooks/$stage
    if ! [ -f "$f" ]; then
	echo "missing hook: $f (please run pre-commit install)"
	exit 1
    fi

    if ! grep -q "File generated by pre-commit" "$f"; then
	echo "not a pre-commit framework hook: $f"
	exit 1
    fi
done
